Add versioned apk generation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,9 +35,16 @@ jobs:
           BETTER_AUTH_SECRET: this_is_for_test_the_build_is_safe
         run: bun run build
 
+      - uses: dorny/paths-filter@v3
+        id: changes
+        with:
+          filters: |
+            android-changes:
+              - 'src-tauri/**'
+
   # Build the android app, this should be optional
   android:
-    if: github.ref == 'refs/heads/main'
+    if: (github.ref == 'refs/heads/main' && steps.changes.outputs.android-changes == 'true') || ${{ github.event_name == 'workflow_dispatch' }}
     runs-on: ubuntu-latest
     needs: [build]
     steps:
@@ -139,30 +146,43 @@ jobs:
       #   run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
 
       # Move apk
-      - name: Rename APK
-        run: |
-          APK_DIR="src-tauri/gen/android/app/build/outputs/apk/universal/release"
-          APK_FILE=$(ls $APK_DIR/*.apk | head -n 1)
+      # - name: Rename APK
+      #   run: |
+      #     APK_DIR="src-tauri/gen/android/app/build/outputs/apk/universal/release"
+      #     APK_FILE=$(ls $APK_DIR/*.apk | head -n 1)
 
-          if [ ! -f "$APK_FILE" ]; then
-            echo "APK not found in $APK_DIR"
-            exit 1
-          fi
+      #     if [ ! -f "$APK_FILE" ]; then
+      #       echo "APK not found in $APK_DIR"
+      #       exit 1
+      #     fi
 
-          mv "$APK_FILE" "etoshokan.apk"
+      #     mv "$APK_FILE" "etoshokan.apk"
+
+      # Move apk
+      - name: 'Generate apk with version'
+        id: prepare-apk
+        run: ./scripts/prepare-apk.js
 
       # Upload apk
       - uses: actions/upload-artifact@v4
         with:
           name: etoshokan-apk
-          path: 'etoshokan.apk'
+          path: steps.prepare-apk.outputs.apk-path
 
       # Create release
+      # - name: Create Release
+      #   uses: softprops/action-gh-release@v2
+      #   with:
+      #     name: Release Etoshokan
+      #     tag_name: dev
+      #     overwrite_files: true
+      #     files: |
+      #       etoshokan.apk
+
       - name: Create Release
-        uses: softprops/action-gh-release@v2
-        with:
-          name: Release Etoshokan
-          tag_name: dev
-          overwrite_files: true
-          files: |
-            etoshokan.apk
+        env:
+          VERSION: ${{ steps.prepare-apk.outputs.apk-version }}
+          APK_PATH: ${{ steps.prepare-apk.outputs.apk-path }}
+          NOTES: Released at $(date -u '+%Y-%m-%d %H:%M:%S') UTC
+        run: |
+          gh release create --tag "$VERSION" --title "$VERSION" --notes "$NOTES" "$APK_PATH"
